import React, { useEffect, useState, useRef } from 'react';
import {
  getReportSummary,
  getEquipmentReport,
  getEventsReport,
  getAllocationsReport,
  getSalesReport,
} from '../api/apiService';

const TABS = [
  { key: 'equipment',   label: 'Equipment Report' },
  { key: 'events',      label: 'Events Report' },
  { key: 'allocations', label: 'Allocations Report' },
  { key: 'sales',       label: 'Sales Report' },
];

export default function Reports() {
  const [activeTab, setActiveTab]       = useState('equipment');
  const [summary, setSummary]           = useState(null);
  const [equipment, setEquipment]       = useState([]);
  const [events, setEvents]             = useState([]);
  const [allocations, setAllocations]   = useState([]);
  const [sales, setSales]               = useState([]);
  const [loading, setLoading]           = useState(true);
  const [error, setError]               = useState('');
  const printRef                        = useRef();

  useEffect(() => {
    const load = async () => {
      try {
        setLoading(true);
        const [s, eq, ev, al, sl] = await Promise.all([
          getReportSummary(),
          getEquipmentReport(),
          getEventsReport(),
          getAllocationsReport(),
          getSalesReport(),
        ]);
        setSummary(s);
        setEquipment(eq);
        setEvents(ev);
        setAllocations(al);
        setSales(sl);
      } catch {
        setError('Failed to load report data. Make sure you are logged in as Admin.');
      } finally {
        setLoading(false);
      }
    };
    load();
  }, []);

  const handlePrint = () => {
    const printContent = printRef.current.innerHTML;
    const win = window.open('', '_blank');
    win.document.write(`
      <!DOCTYPE html>
      <html>
      <head>
        <title>Atlas EMS — ${TABS.find(t => t.key === activeTab)?.label}</title>
        <style>
          * { margin: 0; padding: 0; box-sizing: border-box; }
          body { font-family: Arial, sans-serif; font-size: 12px; color: #1a1a1a; padding: 24px; }
          .print-header { border-bottom: 3px solid #42103C; padding-bottom: 12px; margin-bottom: 20px; }
          .print-header h1 { font-size: 20px; color: #42103C; }
          .print-header p  { font-size: 11px; color: #666; margin-top: 4px; }
          .summary-grid { display: grid; grid-template-columns: repeat(4,1fr); gap: 10px; margin-bottom: 20px; }
          .stat-card { border: 1px solid #D9C4D7; border-radius: 6px; padding: 10px; }
          .stat-card .stat-label { font-size: 10px; color: #666; text-transform: uppercase; }
          .stat-card .stat-value { font-size: 22px; font-weight: bold; color: #42103C; }
          table { width: 100%; border-collapse: collapse; margin-top: 12px; }
          th { background: #42103C; color: #fff; padding: 7px 10px; text-align: left; font-size: 11px; }
          td { padding: 6px 10px; border-bottom: 1px solid #eee; font-size: 11px; }
          tr:nth-child(even) td { background: #F5EEF4; }
          .badge { display: inline-block; padding: 2px 8px; border-radius: 10px; font-size: 10px; font-weight: bold; }
          .badge-stock   { background: #e8f5e9; color: #1B5E20; }
          .badge-reserve { background: #FFF3E0; color: #E65100; }
          .badge-deploy  { background: #E3F2FD; color: #0D47A1; }
          .badge-return  { background: #F3E5F5; color: #4A148C; }
          .badge-low     { background: #FFEBEE; color: #B71C1C; }
          .footer { margin-top: 30px; border-top: 1px solid #D9C4D7; padding-top: 8px; font-size: 10px; color: #999; }
        </style>
      </head>
      <body>
        <div class="print-header">
          <h1>Atlas Inventory &amp; Event Resource Management System</h1>
          <p>Generated by Atlas EMS Admin Panel &nbsp;|&nbsp; ${new Date().toLocaleDateString('en-GB', { day:'2-digit', month:'long', year:'numeric' })} &nbsp;|&nbsp; Confidential — Admin Use Only</p>
        </div>
        ${printContent}
        <div class="footer">Atlas Turbo LTD &nbsp;|&nbsp; Kigali, Rwanda &nbsp;|&nbsp; This report is system-generated and reflects current data.</div>
      </body>
      </html>
    `);
    win.document.close();
    win.focus();
    win.print();
  };

  if (loading) return <div className="page-loading">Loading reports…</div>;
  if (error)   return <div className="alert alert-error">{error}</div>;

  const statusBadge = (status) => {
    const map = {
      IN_STOCK:  { cls: 'badge-stock',   label: 'In Stock' },
      RESERVED:  { cls: 'badge-reserve', label: 'Reserved' },
      DEPLOYED:  { cls: 'badge-deploy',  label: 'Deployed' },
      RETURNED:  { cls: 'badge-return',  label: 'Returned' },
      PLANNED:   { cls: 'badge-stock',   label: 'Planned' },
      IN_PROGRESS:{ cls: 'badge-deploy', label: 'In Progress' },
      COMPLETED: { cls: 'badge-return',  label: 'Completed' },
    };
    const b = map[status] || { cls: 'badge-stock', label: status };
    return <span className={`report-badge ${b.cls}`}>{b.label}</span>;
  };

  return (
    <div className="reports-page">
      {/* ── Page Header ── */}
      <div className="reports-header">
        <div>
          <h1 className="reports-title">Reports</h1>
          <p className="reports-sub">Admin-only — system data as of {new Date().toLocaleDateString('en-GB', { day:'2-digit', month:'long', year:'numeric' })}</p>
        </div>
        <button className="btn-print" onClick={handlePrint}>
          Print / Export
        </button>
      </div>

      {/* ── Summary Cards ── */}
      {summary && (
        <div className="report-summary-grid">
          <div className="report-stat-card purple">
            <div className="stat-value">{summary.totalEquipment}</div>
            <div className="stat-label">Equipment Types</div>
            <div className="stat-sub">{summary.totalUnits} total units · {summary.availableUnits} available</div>
          </div>
          <div className="report-stat-card orange">
            
            <div className="stat-value">{summary.totalEvents}</div>
            <div className="stat-label">Events</div>
            <div className="stat-sub">{summary.plannedEvents} planned · {summary.inProgressEvents} in progress</div>
          </div>
          <div className="report-stat-card purple">
            <div className="stat-value">{summary.totalAllocations}</div>
            <div className="stat-label">Allocations</div>
            <div className="stat-sub">{summary.deployedAllocations} deployed · {summary.returnedAllocations} returned</div>
          </div>
          <div className="report-stat-card orange">
            <div className="stat-value">{summary.lowStockCount}</div>
            <div className="stat-label">Low Stock Alerts</div>
            <div className="stat-sub">Equipment at ≤ 2 units available</div>
          </div>
          <div className="report-stat-card purple">
            <div className="stat-value">{summary.totalSales}</div>
            <div className="stat-label">Sales Recorded</div>
            <div className="stat-sub">{summary.totalUnitsSold} total units sold</div>
          </div>
        </div>
      )}

      {/* ── Tab Switcher ── */}
      <div className="report-tabs">
        {TABS.map(tab => (
          <button
            key={tab.key}
            className={`report-tab-btn ${activeTab === tab.key ? 'active' : ''}`}
            onClick={() => setActiveTab(tab.key)}
          >
            {tab.label}
          </button>
        ))}
      </div>

      {/* ── Printable Content ── */}
      <div ref={printRef}>

        {/* Summary section for print */}
        {summary && (
          <div className="summary-grid print-only-block" style={{ display: 'none' }}>
            <div className="stat-card"><div className="stat-label">Total Equipment</div><div className="stat-value">{summary.totalEquipment}</div></div>
            <div className="stat-card"><div className="stat-label">Total Units</div><div className="stat-value">{summary.totalUnits}</div></div>
            <div className="stat-card"><div className="stat-label">Total Events</div><div className="stat-value">{summary.totalEvents}</div></div>
            <div className="stat-card"><div className="stat-label">Total Allocations</div><div className="stat-value">{summary.totalAllocations}</div></div>
          </div>
        )}

        {/* ── Equipment Table ── */}
        {activeTab === 'equipment' && (
          <div className="report-table-section">
            <h2 className="report-section-title">Equipment Report <span className="report-count">{equipment.length} items</span></h2>
            <table className="report-table">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Equipment Name</th>
                  <th>Category</th>
                  <th>Total Qty</th>
                  <th>Available</th>
                  <th>Allocated</th>
                  <th>Status</th>
                  <th>Stock Alert</th>
                </tr>
              </thead>
              <tbody>
                {equipment.length === 0 && (
                  <tr><td colSpan={8} className="report-empty">No equipment found.</td></tr>
                )}
                {equipment.map((eq, i) => (
                  <tr key={eq.id}>
                    <td className="report-id">{i + 1}</td>
                    <td><strong>{eq.name}</strong></td>
                    <td>{eq.categoryName}</td>
                    <td className="report-num">{eq.totalQuantity}</td>
                    <td className="report-num">{eq.availableQuantity}</td>
                    <td className="report-num">{eq.allocatedQuantity}</td>
                    <td>{statusBadge(eq.status)}</td>
                    <td>
                      {eq.lowStock
                        ? <span className="report-badge badge-low">⚠ Low Stock</span>
                        : <span className="report-badge badge-ok">✓ OK</span>}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}

        {/* ── Events Table ── */}
        {activeTab === 'events' && (
          <div className="report-table-section">
            <h2 className="report-section-title">Events Report <span className="report-count">{events.length} events</span></h2>
            <table className="report-table">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Event Name</th>
                  <th>Venue</th>
                  <th>Date</th>
                  <th>Status</th>
                  <th>Allocations</th>
                  <th>Units Allocated</th>
                  <th>Deployed</th>
                  <th>Returned</th>
                </tr>
              </thead>
              <tbody>
                {events.length === 0 && (
                  <tr><td colSpan={9} className="report-empty">No events found.</td></tr>
                )}
                {events.map((ev, i) => (
                  <tr key={ev.id}>
                    <td className="report-id">{i + 1}</td>
                    <td><strong>{ev.name}</strong></td>
                    <td>{ev.venue}</td>
                    <td>{ev.eventDate}</td>
                    <td>{statusBadge(ev.status)}</td>
                    <td className="report-num">{ev.totalAllocations}</td>
                    <td className="report-num">{ev.totalUnitsAllocated}</td>
                    <td className="report-num">{ev.deployedAllocations}</td>
                    <td className="report-num">{ev.returnedAllocations}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}

        {/* ── Sales Table ── */}
        {activeTab === 'sales' && (
          <div className="report-table-section">
            <h2 className="report-section-title">Sales Report <span className="report-count">{sales.length} records</span></h2>
            <table className="report-table">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Equipment</th>
                  <th>Category</th>
                  <th>Qty Sold</th>
                  <th>Date Sold</th>
                  <th>Buyer</th>
                  <th>Notes</th>
                </tr>
              </thead>
              <tbody>
                {sales.length === 0 && (
                  <tr><td colSpan={7} className="report-empty">No sales recorded yet.</td></tr>
                )}
                {sales.map((s, i) => (
                  <tr key={s.id}>
                    <td className="report-id">{i + 1}</td>
                    <td><strong>{s.equipmentName}</strong></td>
                    <td>{s.categoryName}</td>
                    <td className="report-num">{s.quantitySold}</td>
                    <td>{s.saleDate}</td>
                    <td>{s.buyerName || '—'}</td>
                    <td>{s.notes || '—'}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}

        {/* ── Allocations Table ── */}
        {activeTab === 'allocations' && (
          <div className="report-table-section">
            <h2 className="report-section-title">Allocations Report <span className="report-count">{allocations.length} records</span></h2>
            <table className="report-table">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Equipment</th>
                  <th>Event</th>
                  <th>Venue</th>
                  <th>Qty Allocated</th>
                  <th>Status</th>
                </tr>
              </thead>
              <tbody>
                {allocations.length === 0 && (
                  <tr><td colSpan={6} className="report-empty">No allocations found.</td></tr>
                )}
                {allocations.map((al, i) => (
                  <tr key={al.id}>
                    <td className="report-id">{i + 1}</td>
                    <td><strong>{al.equipmentName}</strong></td>
                    <td>{al.eventName}</td>
                    <td>{al.eventVenue}</td>
                    <td className="report-num">{al.quantityAllocated}</td>
                    <td>{statusBadge(al.status)}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
}
